const navItems=[['dashboard','Tổng quan','layout-dashboard'],['keys','API Keys','key-round'],['packages','Packages','layers-3'],['analytics','Analytics','chart-no-axes-combined'],['docs','Tài liệu','book-open'],['pricing','Gói dịch vụ','badge-dollar-sign'],['settings','Cài đặt','settings-2']];
const FIREBASE_DB_URL='https://authsever-91133-default-rtdb.asia-southeast1.firebasedatabase.app';
const FIREBASE_AUTH_TOKEN='';
const DEFAULT_DB={keys:[{id:1,key:'NC-7K2A-9P4X',package:'ChatGPT iOS',status:'active',expires:'2026-12-31T23:59',starts:'2026-01-01T00:00',devices:2,maxDevices:5,requests:12840,notes:'Production',deviceLock:false}],packages:[{id:1,name:'ChatGPT iOS',version:'1.4.0',status:'active',devices:126,maxDevices:500,keys:1,token:'pk_live_NCIO_7Qm4Z8v2K9x5P3r6T1y8W4n7C2s6D9f5H8J3L7M2Q6V9X4Z8',expires:'2027-12-31T23:59',notes:'Production package'}],messages:[]};
function storageGet(key,fallback=''){try{return localStorage.getItem(key)??fallback}catch(e){return fallback}}
function storageSet(key,value){try{localStorage.setItem(key,value);return true}catch(e){console.warn('Storage unavailable',e);return false}}
function readLocalDb(){try{const raw=storageGet('nc-auth-db');if(!raw)return JSON.parse(JSON.stringify(DEFAULT_DB));const parsed=JSON.parse(raw);return normalizeDb(parsed)}catch(e){console.warn('Invalid local data',e);return JSON.parse(JSON.stringify(DEFAULT_DB))}}
function normalizeDb(raw){const x=raw&&typeof raw==='object'?raw:{};return{keys:Array.isArray(x.keys)?x.keys.map((k,i)=>({id:k.id??Date.now()+i,key:String(k.key??''),package:String(k.package??''),status:k.status==='paused'?'paused':'active',expires:String(k.expires??''),starts:String(k.starts??''),deviceUids:Array.isArray(k.deviceUids)?k.deviceUids.map(v=>String(v).trim()).filter(Boolean):[],devices:Math.max(0,Number(k.devices)||0),maxDevices:Math.max(1,Number(k.maxDevices)||1),requests:Math.max(0,Number(k.requests)||0),notes:String(k.notes??''),deviceLock:!!k.deviceLock})):[],packages:Array.isArray(x.packages)?x.packages.map((p,i)=>({id:p.id??Date.now()+i,name:String(p.name??''),version:String(p.version??''),status:p.status==='paused'?'paused':'active',devices:Math.max(0,Number(p.devices)||0),maxDevices:Math.max(1,Number(p.maxDevices)||1),keys:Math.max(0,Number(p.keys)||0),token:(String(p.token??'').length>=40?String(p.token):makePackageToken()),expires:String(p.expires??''),notes:String(p.notes??'')})):[],messages:Array.isArray(x.messages)?x.messages.map((m,i)=>({id:m.id??Date.now()+i,keyId:m.keyId??null,key:String(m.key??''),title:String(m.title??''),body:String(m.body??''),type:String(m.type??'info'),createdAt:String(m.createdAt??new Date().toISOString()),expiresAt:String(m.expiresAt??''),read:!!m.read})):[]}}
let db=readLocalDb(); db.keys.forEach(k=>{if(!Array.isArray(k.deviceUids))k.deviceUids=[]; if(k.deviceUids.length)k.devices=k.deviceUids.length});
let state={page:'dashboard',edit:null,keyFilter:'all',selectedKeys:[],docsTab:'Overview',generatedSuffix:''};
function firebaseUrl(path){let u=FIREBASE_DB_URL.replace(/\/$/,'')+'/'+path+'.json';return FIREBASE_AUTH_TOKEN?u+'?auth='+encodeURIComponent(FIREBASE_AUTH_TOKEN):u}
function setFirebaseStatus(text,ok){let e=document.getElementById('firebaseStatus');if(e){e.textContent=text;e.style.color=ok?'var(--good)':'var(--warn)'}}
async function firebaseGet(path){let r=await fetch(firebaseUrl(path),{cache:'no-store'});if(!r.ok)throw new Error('Firebase GET '+r.status);return r.json()}
async function firebasePut(path,data){let r=await fetch(firebaseUrl(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('Firebase PUT '+r.status);return r.json()}
async function loadFirebase(){setFirebaseStatus('Đang tải…',false);try{let remote=await firebaseGet('nc_auth');if(remote&&typeof remote==='object'){let rawPackages=Array.isArray(remote.packages)?remote.packages:db.packages;let hadShortToken=rawPackages.some(p=>String(p?.token??'').length<40);db=normalizeDb({keys:Array.isArray(remote.keys)?remote.keys:db.keys,packages:rawPackages,messages:Array.isArray(remote.messages)?remote.messages:db.messages}); db.keys.forEach(k=>{if(!Array.isArray(k.deviceUids))k.deviceUids=[]; if(k.deviceUids.length)k.devices=k.deviceUids.length});storageSet('nc-auth-db',JSON.stringify(db));renderNav();renderCurrent();if(hadShortToken)await firebasePut('nc_auth',{keys:db.keys,packages:db.packages,messages:db.messages,updatedAt:new Date().toISOString()})}setFirebaseStatus('Firebase ✓',true)}catch(e){console.warn(e);setFirebaseStatus('Firebase offline',false);toast('Không đọc được Firebase — đang dùng dữ liệu local')}}
async function syncFirebase(){try{setFirebaseStatus('Đang lưu…',false);await firebasePut('nc_auth',{keys:db.keys,packages:db.packages,messages:db.messages,updatedAt:new Date().toISOString()});setFirebaseStatus('Firebase ✓',true);return true}catch(e){console.error(e);setFirebaseStatus('Lưu lỗi',false);toast('Firebase chưa cho phép ghi dữ liệu');return false}}
function save(){db=normalizeDb(db);storageSet('nc-auth-db',JSON.stringify(db));syncFirebase()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(m){let e=document.getElementById('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2500)}
function toggleSide(){document.getElementById('sidebar').classList.toggle('open')}
function go(p){state.page=p;document.getElementById('sidebar').classList.remove('open');if(!['keys','packages'].includes(p))document.getElementById('globalSearch').value='';renderNav();renderCurrent()}
function renderNav(){document.getElementById('nav').innerHTML=navItems.map(([id,l,i])=>{let active=state.page===id||(id==='keys'&&state.page==='key-form')||(id==='packages'&&state.page==='package-form');return `<button class="${active?'active':''}" onclick="go('${id}')"><span class="nav-icon"><i data-lucide="${i}"></i></span><span>${l}</span>${id==='keys'?'<span class="badge">'+db.keys.length+'</span>':''}</button>`}).join(''); if(window.lucide)lucide.createIcons();}
function toggleTheme(){document.body.classList.toggle('light');storageSet('nc-theme',document.body.classList.contains('light')?'light':'dark')}
function stat(label,val,delta){return `<div class="card"><div class="stat-label">${label}</div><div class="stat">${val}</div><div class="delta">${delta}</div></div>`}
function dashboard(){let req=db.keys.reduce((a,k)=>a+(Number(k.requests)||0),0);return `<div class="eyebrow">Nguyễn Cường iOS</div><h1 class="title">Xin chào, Developer 👋</h1><div class="sub">Quản lý KeyAuth, package và hoạt động API trong một workspace.</div><div class="hero"><div><span class="tag">PRO WORKSPACE</span><h2>iOS KeyAuth Manager</h2><p>Không cần đăng nhập. Dữ liệu demo được lưu trực tiếp trên thiết bị bằng localStorage.</p></div><div class="actions"><button class="primary" onclick="openKey()">+ Tạo API Key</button><button class="secondary" onclick="go('docs')">Xem tài liệu</button></div></div><div class="stats">${stat('Packages',db.packages.length,'↑ Workspace')} ${stat('API Keys',db.keys.length,'↑ Quản lý')} ${stat('Requests',req.toLocaleString(),'↑ Tổng requests')} ${stat('Hoạt động','99.9%','● Hệ thống ổn định')}</div><div class="grid2"><div class="card"><h3>API usage • 7 ngày</h3><div class="chart">${[42,58,46,74,61,89,68,78,54,91,70,84,63,76].map(v=>`<div class="bar" style="height:${v}%"></div>`).join('')}</div></div><div class="card"><h3>Hoạt động gần đây</h3><div class="activity">${db.keys.slice(0,4).map(k=>`<div class="activity-row"><span>Key <b>${esc(k.key)}</b><br><span class="muted">${esc(k.package)}</span></span><span class="muted">vừa xong</span></div>`).join('')||'<div class="empty">Chưa có hoạt động</div>'}</div></div></div>`}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'});}
function keyExpiryClass(v){if(!v)return '';const t=new Date(v).getTime();if(!Number.isFinite(t))return '';return t<Date.now()?'expired':t-Date.now()<7*864e5?'soon':''}
function keys(){
  let q=(document.getElementById('globalSearch').value||'').toLowerCase();
  let rows=db.keys.filter(k=>Object.values(k).join(' ').toLowerCase().includes(q));
  rows=rows.filter(k=>!state.keyFilter||state.keyFilter==='all'||k.status===state.keyFilter);
  let unread=db.messages.filter(m=>!m.read).length;
  let selected=new Set(state.selectedKeys||[]);
  let visibleIds=rows.map(k=>k.id);
  let allVisible=visibleIds.length>0&&visibleIds.every(id=>selected.has(id));
  return `<div class="eyebrow">Management</div><div class="page-head"><div><h1 class="title">API Keys</h1><div class="sub">Quản lý key, thời hạn, UID thiết bị, trạng thái và nhắn tin trực tiếp.</div></div><button class="primary" onclick="openKey()">＋ Tạo API Key</button></div>
  <div class="metric-strip"><div><b>${db.keys.length}</b><span>Tổng key</span></div><div><b>${db.keys.filter(k=>k.status==='active').length}</b><span>Đang hoạt động</span></div><div><b>${db.keys.filter(k=>keyExpiryClass(k.expires)==='soon').length}</b><span>Sắp hết hạn</span></div><div><b>${unread}</b><span>Thông báo chưa đọc</span></div></div>
  <div class="toolbar"><div class="toolbar-left"><input class="input" placeholder="Tìm key, package, UID, ghi chú..." value="${esc(q)}" oninput="document.getElementById('globalSearch').value=this.value;renderCurrent()"><select class="select" onchange="state.keyFilter=this.value;renderCurrent()"><option value="all">Tất cả trạng thái</option><option value="active" ${state.keyFilter==='active'?'selected':''}>Active</option><option value="paused" ${state.keyFilter==='paused'?'selected':''}>Paused</option></select></div><div class="toolbar-right"><button class="secondary" onclick="selectVisibleKeys()">${allVisible?'Bỏ chọn':'Chọn trang'}</button><button class="secondary danger" onclick="deleteSelectedKeys()" ${selected.size?'':'disabled'}>Xóa ${selected.size?selected.size:''} key</button><button class="secondary danger" onclick="deleteAllKeys()" ${db.keys.length?'':'disabled'}>Xóa ALL KEY</button><button class="secondary" onclick="exportKeys()">Xuất CSV</button></div></div>
  <div class="selection-info">${selected.size?`Đã chọn <b>${selected.size}</b> key`:'Chưa chọn key nào'} ${selected.size?'<button class="text-btn" onclick="clearKeySelection()">Bỏ chọn tất cả</button>':''}</div>
  <div class="table-wrap"><table class="table detailed"><thead><tr><th><input type="checkbox" ${allVisible?'checked':''} onchange="toggleAllVisibleKeys(this.checked)"></th><th>KEY</th><th>PACKAGE</th><th>TRẠNG THÁI</th><th>THỜI HẠN</th><th>THIẾT BỊ / UID</th><th>REQUESTS</th><th>TIN NHẮN</th><th></th></tr></thead><tbody>
  ${rows.map(k=>{let msgs=db.messages.filter(m=>m.keyId===k.id);let uids=Array.isArray(k.deviceUids)?k.deviceUids.filter(Boolean):[];let count=Math.max(uids.length,Number(k.devices)||0);return `<tr><td><input type="checkbox" ${selected.has(k.id)?'checked':''} onchange="toggleKeySelection(${k.id},this.checked)"></td><td><b>${esc(k.key)}</b><div class="mini">${esc(k.notes||'Không có ghi chú')}</div></td><td><b>${esc(k.package)}</b><div class="mini">Lock: ${k.deviceLock?'Bật':'Tắt'}</div></td><td><span class="pill ${k.status==='active'?'green':'pink'}"><i class="status-dot"></i>${k.status==='active'?'Active':'Paused'}</span></td><td><span class="expiry ${keyExpiryClass(k.expires)}">${fmtDate(k.expires)}</span><div class="mini">Từ ${fmtDate(k.starts)}</div></td><td><b>${count}/${k.maxDevices}</b><div class="mini">${uids.length?`<details class="uid-details"><summary>${uids.length} UID máy</summary>${uids.map(u=>`<code>${esc(u)}</code>`).join('')}${uids.length>6?'<span class="mini">…</span>':''}</details>`:'Chưa có UID'}</div></td><td>${(Number(k.requests)||0).toLocaleString()}</td><td><button class="icon-btn" title="Nhắn tin" onclick="openMessage(${k.id})">✉ ${msgs.length}</button></td><td><div class="row-actions"><button class="secondary" onclick="editKey(${k.id})">Sửa</button><button class="secondary" onclick="toggleKey(${k.id})">${k.status==='active'?'Pause':'Resume'}</button><button class="secondary danger" onclick="deleteKey(${k.id})">Xóa</button></div></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty">Không tìm thấy API key.</div></td></tr>'}</tbody></table></div>`}

function packages(){let keyCounts=db.keys.reduce((m,k)=>(m[k.package]=(m[k.package]||0)+1,m),{});let q=(document.getElementById('globalSearch').value||'').toLowerCase();let rows=db.packages.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));return `<div class="eyebrow">Workspace</div><div class="page-head"><div><h1 class="title">Packages</h1><div class="sub">Quản lý package, version, token, giới hạn thiết bị và thời hạn phát hành.</div></div><button class="primary" onclick="openPackage()">＋ Tạo Package</button></div><div class="metric-strip"><div><b>${db.packages.length}</b><span>Packages</span></div><div><b>${db.packages.filter(p=>p.status==='active').length}</b><span>Active</span></div><div><b>${db.packages.reduce((a,p)=>a+(p.devices||0),0).toLocaleString()}</b><span>Thiết bị</span></div><div><b>${db.keys.length}</b><span>API Keys</span></div></div><div class="toolbar"><input class="input" placeholder="Tìm package, version, token..." value="${esc(q)}" oninput="document.getElementById('globalSearch').value=this.value;renderCurrent()"></div><div class="package-grid">${rows.map(p=>`<article class="package-card"><div class="package-top"><span class="package-icon">◈</span><span class="pill ${p.status==='active'?'green':'pink'}">${p.status}</span></div><h3>${esc(p.name)}</h3><p class="muted">v${esc(p.version)} · ${esc(p.notes||'Production package')}</p><div class="package-token"><span>Token</span><code>${esc(p.token)}</code><button class="icon-btn" onclick="copyText('${esc(p.token)}')">Copy</button></div><div class="package-stats"><div><b>${keyCounts[p.name]||0}</b><span>Keys</span></div><div><b>${p.devices}/${p.maxDevices}</b><span>Devices</span></div><div><b>${fmtDate(p.expires)}</b><span>Expires</span></div></div><div class="row-actions"><button class="secondary" onclick="editPackage(${p.id})">Chỉnh sửa</button><button class="secondary" onclick="togglePackage(${p.id})">${p.status==='active'?'Pause':'Resume'}</button><button class="secondary danger" onclick="deletePackage(${p.id})">Xóa</button></div></article>`).join('')||'<div class="card empty">Chưa có package.</div>'}</div>`}
function analytics(){let total=db.keys.reduce((a,k)=>a+(Number(k.requests)||0),0);return `<div class="eyebrow">Insights</div><h1 class="title">Analytics</h1><div class="sub">Theo dõi requests và trạng thái workspace.</div><div class="stats">${stat('Requests',total.toLocaleString(),'7 ngày')} ${stat('Errors','0.08%','↓ 12%')} ${stat('Latency','84 ms','↓ 9 ms')} ${stat('Uptime','99.9%','Ổn định')}</div><div class="grid2"><div class="card"><h3>Requests theo ngày</h3><div class="chart">${[35,44,57,51,68,73,62,79,84,71,88,91,76,86,94].map(v=>`<div class="bar" style="height:${v}%"></div>`).join('')}</div></div><div class="card"><h3>Top packages</h3><div class="activity">${db.packages.map((p,i)=>`<div class="activity-row"><b>${esc(p.name)}</b><span>${((Number(p.devices)||0)*97).toLocaleString()} req</span></div>`).join('')||'<div class="empty">Chưa có dữ liệu</div>'}</div></div></div>`}
function docs(){let tab=state.docsTab||'Overview';let samples={Overview:`// KeyAuth integration\nlet auth = Auth.shared\nauth.authenticate("YOUR_TOKEN") { result in\n    if result.isSuccess {\n        print("Authenticated")\n    }\n}`,"API Reference":`authenticate(token)\n// Validate a key/token against your service.\n\nrevoke(key)\n// Revoke an active key.\n\nstatus(key)\n// Read key status and expiration.`,SDK:`// iOS / Theos\n// Keep the SDK token in your protected configuration.\n\nAuth.shared.authenticate("YOUR_TOKEN")`,Examples:`// Example flow\ncreate package\n  -> create API key\n  -> authenticate\n  -> check expiration\n  -> handle revoked / paused state`};let code=samples[tab];return `<div class="eyebrow">Developer</div><h1 class="title">Tài liệu</h1><div class="sub">Tích hợp nhanh trong dự án iOS / Theos.</div><div class="docs-tabs">${Object.keys(samples).map(t=>`<button class="${tab===t?'active':''}" onclick="setDocsTab('${t}')">${t}</button>`).join('')}</div><div class="grid2"><div class="card"><h3>${tab}</h3><p class="muted">${tab==='Overview'?'1. Tạo package → 2. Tạo API key → 3. Đưa token vào SDK → 4. Gọi authenticate.':tab==='API Reference'?'Các method cơ bản cho luồng xác thực và quản lý key.':tab==='SDK'?'Thông tin tương thích và cách khởi tạo SDK.':'Luồng mẫu từ tạo package đến xác thực.'}</p><button class="primary" onclick="copyCode()">Copy example</button></div><div class="card"><h3>Example</h3><pre class="code" id="code">${esc(code)}</pre></div></div><div class="card" style="margin-top:14px"><h3>SDK compatibility</h3><p class="muted">iOS 12+ • arm64 • arm64e • Keychain • expired-key handling • REST/RTDB dashboard.</p></div>`}
function setDocsTab(tab){state.docsTab=tab;renderCurrent()}

function pricing(){let plans=[['Free','0','Cho dự án cá nhân'],['Developer','9','Dành cho developer'],['Seller','29','Quản lý nhiều package'],['SupperSeller','79','Workspace nâng cao']];return `<div class="eyebrow">Plans</div><h1 class="title">Gói dịch vụ</h1><div class="sub">Chọn workspace phù hợp. Demo này xử lý nâng cấp bằng thông báo cục bộ.</div><div class="price-grid">${plans.map((p,i)=>`<div class="card price ${i===1?'pop':''}">${i===1?'<span class="tag">PHỔ BIẾN</span>':''}<h3>${p[0]}</h3><strong>$${p[1]}</strong><span class="muted"> / tháng</span><p class="muted">${p[2]}</p><ul><li>API key management</li><li>Package management</li><li>Analytics</li><li>Documentation</li></ul><button class="${i===1?'primary':'secondary'}" onclick="toast('${p[0]}: nâng cấp demo đã sẵn sàng')">${i===0?'Đang dùng':'Nâng cấp'}</button></div>`).join('')}</div>`}
function settings(){let light=document.body.classList.contains('light');return `<div class="eyebrow">Workspace</div><h1 class="title">Cài đặt</h1><div class="sub">Tuỳ chỉnh giao diện và đồng bộ dữ liệu với Firebase Realtime Database.</div><div class="settings-grid"><div class="card"><h3>Giao diện</h3><div class="setting"><div><b>Chế độ sáng</b><small>Đổi dark / light</small></div><button class="switch ${light?'on':''}" onclick="toggleTheme();renderCurrent()"><i></i></button></div><div class="setting"><div><b>Màu nhấn</b><small>Pink • #ff3d91</small></div><span class="pill pink">PINK</span></div></div><div class="card"><h3>Firebase Realtime Database</h3><div class="setting"><div><b>Kết nối</b><small>authsever-91133-default-rtdb • /nc_auth</small></div><span class="pill pink">RTDB</span></div><div class="setting"><div><b>Đồng bộ</b><small>Mỗi lần tạo/sửa/xóa key hoặc package sẽ lưu lên Firebase.</small></div><button class="secondary" onclick="loadFirebase()">Sync</button></div></div><div class="card"><h3>Hồ sơ & dữ liệu</h3><div class="setting"><div><b>Tên hiển thị</b><small>Được lưu trên thiết bị</small></div><button class="secondary" onclick="editName()">Sửa</button></div><div class="setting"><div><b>Backup JSON</b><small>Xuất dữ liệu local</small></div><button class="secondary" onclick="backup()">Xuất</button></div><div class="setting"><div><b>Xoá dữ liệu demo</b><small>Không thể hoàn tác</small></div><button class="secondary" onclick="resetData()">Reset</button></div></div></div>`}
function refreshIcons(){try{if(window.lucide)lucide.createIcons({attrs:{'stroke-width':1.8}})}catch(e){}}
function refreshIcons(){try{if(window.lucide)lucide.createIcons({attrs:{'stroke-width':1.8}})}catch(e){}}
function renderCurrent(){let fn={dashboard,keys,packages,analytics,docs,pricing,settings,'key-form':keyForm,'package-form':packageForm}[state.page]||dashboard;document.getElementById('content').innerHTML=fn();document.getElementById('mobileTitle').textContent=navItems.find(x=>x[0]===state.page)?.[1]||'Tổng quan';document.getElementById('profileName').textContent=storageGet('display-name','Developer')||'Developer';refreshIcons()}
function modal(title,body){document.getElementById('modal').innerHTML=`<h3>${title}</h3>${body}<div class="modal-actions"><button class="secondary" onclick="closeModal()">Hủy</button><button class="primary" id="modalSave">Lưu</button></div>`;document.getElementById('modalBg').classList.add('show')}
function closeModal(){document.getElementById('modalBg').classList.remove('show')}
function localInputDate(v){if(!v)return '';let d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,16);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function slugPart(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'').slice(0,28)||'PACKAGE'}
function lettersPart(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z]/g,'').slice(0,28)||'KEY'}
function randomLetters(len=24){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ';let out='';if(window.crypto?.getRandomValues){const a=new Uint32Array(len);crypto.getRandomValues(a);for(let i=0;i<len;i++)out+=chars[a[i]%chars.length]}else for(let i=0;i<len;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out}
function randomAlphaNum(len=18){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';let out='';if(window.crypto?.getRandomValues){const a=new Uint32Array(len);crypto.getRandomValues(a);for(let i=0;i<len;i++)out+=chars[a[i]%chars.length]}else for(let i=0;i<len;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out}
function makePackageToken(){return 'pk_live_'+randomAlphaNum(72)}
function makeKeyValue(keyName,packageName){return `${lettersPart(keyName)}_${randomLetters(24)}`}
function addDuration(value){const input=document.getElementById('fExpires');if(!input)return;if(value==='forever'){input.value='';toast('Đã chọn vô hạn ngày');return}const base=new Date();if(value==='month')base.setMonth(base.getMonth()+1);else if(value==='year')base.setFullYear(base.getFullYear()+1);else base.setDate(base.getDate()+Number(value));input.value=localInputDate(base.toISOString());}
function syncGeneratedKey(){const name=document.getElementById('fKeyName');const pkg=document.getElementById('fPackage');const key=document.getElementById('fKey');if(!name||!pkg||!key)return;if(key.dataset.manual==='1')return;key.value=makeKeyValue(name.value,pkg.value)}
function openKey(id){state.page='key-form';state.edit=id||null;state.generatedSuffix=id?'':randomLetters(24);document.getElementById('sidebar').classList.remove('open');renderNav();renderCurrent()}
function editKey(id){openKey(id)}
function keyForm(){
  const id=state.edit,k=id?db.keys.find(x=>x.id===id):null,currentPkg=k?.package||db.packages[0]?.name||'';
  const keyName=k?String(k.key).split('_')[0]:'KEY';
  const starts=localInputDate(k?.starts||new Date().toISOString());
  const expires=localInputDate(k?.expires||'');
  const uids=Array.isArray(k?.deviceUids)?k.deviceUids.join('\\n'):'';
  return `<div class="form-page"><div class="form-page-head"><div><button class="back-btn" onclick="go('keys')">← API Keys</button><div class="eyebrow">${id?'EDIT KEY':'NEW KEY'}</div><h1 class="title">${id?'Chỉnh sửa API Key':'Tạo API Key'}</h1><div class="sub">Cấu hình key, thời gian, giới hạn thiết bị và UID máy.</div></div><div class="form-page-actions"><button class="secondary" onclick="go('keys')">Hủy</button><button class="primary" onclick="saveKeyForm()">${id?'Lưu thay đổi':'Tạo Key'}</button></div></div>
  <div class="form-layout"><div class="card"><h3>Thông tin Key</h3><div class="form two"><label>Tên Key<input id="fKeyName" maxlength="40" value="${esc(keyName)}" oninput="syncGeneratedKeyPage()" placeholder="VIP"></label><label>Package<select id="fPackage" onchange="syncGeneratedKeyPage()">${db.packages.map(p=>`<option value="${esc(p.name)}" ${p.name===currentPkg?'selected':''}>${esc(p.name)}</option>`).join('')||'<option value="">Chưa có package</option>'}</select></label><label class="full">API Key<input id="fKey" value="${esc(k?.key||makeKeyValue(keyName,currentPkg))}" ${id?'':'readonly'} oninput="this.value=this.value.toUpperCase().replace(/[^A-Z_]/g,'')"><small>Format: TENKEY_RANDOM. Cả tên và phần random chỉ gồm chữ cái IN HOA, không có số hoặc dấu gạch ngang. Khi chỉnh sửa có thể thay trực tiếp key.</small></label><div class="full key-preview"><span>Preview</span><code id="keyPreview">${esc(k?.key||makeKeyValue(keyName,currentPkg))}</code></div></div></div>
  <div class="card"><h3>Thời hạn</h3><div class="quick-expiry"><span>Chọn nhanh</span><div class="quick-buttons"><button type="button" class="secondary" onclick="addDurationPage(1)">1 ngày</button><button type="button" class="secondary" onclick="addDurationPage(3)">3 ngày</button><button type="button" class="secondary" onclick="addDurationPage(7)">7 ngày</button><button type="button" class="secondary" onclick="addDurationPage('month')">1 tháng</button><button type="button" class="secondary" onclick="addDurationPage('year')">1 năm</button><button type="button" class="secondary" onclick="addDurationPage('forever')">Vô hạn</button></div></div><div class="form two"><label>Bắt đầu<input id="fStarts" type="datetime-local" value="${starts}"></label><label>Hết hạn<input id="fExpires" type="datetime-local" value="${expires}"><small>Bỏ trống = vô hạn.</small></label></div></div>
  <div class="card"><h3>Thiết bị & UID</h3><div class="form two"><label>Giới hạn thiết bị<input id="fMaxDevices" type="number" min="1" value="${k?.maxDevices||5}"></label><label>Thiết bị hiện tại<input id="fDevices" type="number" min="0" value="${k?.devices||0}" readonly><small>Tự tính theo số UID nhập bên dưới.</small></label><label class="full">UID máy đã nhập<textarea id="fUids" rows="8" placeholder="Mỗi UID một dòng">${esc(uids)}</textarea><small>${k?'Các UID hiện tại được giữ lại khi sửa.':'Nhập mỗi UID một dòng; số thiết bị sẽ tự tính.'}</small></label><label class="check"><input id="fLock" type="checkbox" ${k?.deviceLock?'checked':''}> Chỉ cho phép thiết bị đã đăng ký</label><label>Trạng thái<select id="fStatus"><option value="active" ${k?.status!=='paused'?'selected':''}>Active</option><option value="paused" ${k?.status==='paused'?'selected':''}>Paused</option></select></label></div></div>
  <div class="card"><h3>Ghi chú</h3><textarea class="wide-textarea" id="fNotes" rows="5" placeholder="Ghi chú nội bộ...">${esc(k?.notes||'')}</textarea></div></div></div>`
}
function syncGeneratedKeyPage(){const name=document.getElementById('fKeyName'),pkg=document.getElementById('fPackage'),key=document.getElementById('fKey'),preview=document.getElementById('keyPreview');if(!name||!pkg||!key)return;const value=`${lettersPart(name.value)}_${state.generatedSuffix||randomLetters(24)}`;if(!state.edit)key.value=value;if(preview)preview.textContent=state.edit?key.value:value}
function addDurationPage(value){const input=document.getElementById('fExpires');if(!input)return;if(value==='forever'){input.value='';return}const d=new Date();if(value==='month')d.setMonth(d.getMonth()+1);else if(value==='year')d.setFullYear(d.getFullYear()+1);else d.setDate(d.getDate()+Number(value));input.value=localInputDate(d.toISOString())}
function saveKeyForm(){const id=state.edit,k=id?db.keys.find(x=>x.id===id):null;const name=document.getElementById('fKeyName').value.trim();const pkg=document.getElementById('fPackage').value;let key=id?document.getElementById('fKey').value.trim().toUpperCase():makeKeyValue(name,pkg); if(id&&!/^[A-Z]+_[A-Z]+$/.test(key)){toast('Key phải có dạng TENKEY_RANDOM, chỉ gồm chữ IN HOA và 1 dấu _');return}const start=document.getElementById('fStarts').value,end=document.getElementById('fExpires').value;const uids=[...new Set(document.getElementById('fUids').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];const max=Math.max(1,Number(document.getElementById('fMaxDevices').value)||1);if(!name||!pkg){toast('Vui lòng nhập tên key và package');return}if(end&&start&&new Date(end)<=new Date(start)){toast('Thời gian hết hạn phải sau thời gian bắt đầu');return}if(uids.length>max){toast(`Có ${uids.length} UID nhưng giới hạn chỉ ${max} thiết bị`);return}if(!id&&db.keys.some(x=>x.key===key)){toast('Key trùng, hãy tạo lại');return}const item={id:k?.id||Date.now(),key,package:pkg,status:document.getElementById('fStatus').value,starts:start,expires:end,deviceUids:uids,devices:uids.length,maxDevices:max,requests:k?.requests||0,notes:document.getElementById('fNotes').value.trim(),deviceLock:document.getElementById('fLock').checked};if(k)Object.assign(k,item);else db.keys.push(item);save();state.edit=null;state.page='keys';renderNav();renderCurrent();toast(id?'Đã cập nhật API Key':'Đã tạo API Key')}
function toggleKey(id){let k=db.keys.find(x=>x.id===id);if(k){k.status=k.status==='active'?'paused':'active';save();renderCurrent();toast(k.status==='active'?'Đã resume key':'Đã pause key')}}
function toggleKeySelection(id,checked){state.selectedKeys=state.selectedKeys||[];if(checked&&!state.selectedKeys.includes(id))state.selectedKeys.push(id);if(!checked)state.selectedKeys=state.selectedKeys.filter(x=>x!==id);renderCurrent()}
function toggleAllVisibleKeys(checked){let q=(document.getElementById('globalSearch').value||'').toLowerCase();let ids=db.keys.filter(k=>Object.values(k).join(' ').toLowerCase().includes(q)).filter(k=>!state.keyFilter||state.keyFilter==='all'||k.status===state.keyFilter).map(k=>k.id);state.selectedKeys=state.selectedKeys||[];if(checked)state.selectedKeys=[...new Set([...state.selectedKeys,...ids])];else state.selectedKeys=state.selectedKeys.filter(id=>!ids.includes(id));renderCurrent()}
function selectVisibleKeys(){let q=(document.getElementById('globalSearch').value||'').toLowerCase();let ids=db.keys.filter(k=>Object.values(k).join(' ').toLowerCase().includes(q)).filter(k=>!state.keyFilter||state.keyFilter==='all'||k.status===state.keyFilter).map(k=>k.id);let all=ids.every(id=>(state.selectedKeys||[]).includes(id));state.selectedKeys=all?(state.selectedKeys||[]).filter(id=>!ids.includes(id)):[...new Set([...(state.selectedKeys||[]),...ids])];renderCurrent()}
function clearKeySelection(){state.selectedKeys=[];renderCurrent()}
function deleteSelectedKeys(){const ids=new Set(state.selectedKeys||[]);if(!ids.size)return;if(!confirm(`Xóa ${ids.size} API key đã chọn?`))return;db.keys=db.keys.filter(k=>!ids.has(k.id));db.messages=db.messages.filter(m=>!ids.has(m.keyId));state.selectedKeys=[];save();renderNav();renderCurrent();toast(`Đã xóa ${ids.size} key`)}
function deleteAllKeys(){if(!db.keys.length)return;if(!confirm(`Xóa toàn bộ ${db.keys.length} API key? Hành động này không thể hoàn tác.`))return;db.keys=[];db.messages=[];state.selectedKeys=[];save();renderNav();renderCurrent();toast('Đã xóa toàn bộ API key')}
function deleteKey(id){if(confirm('Xóa API key này?')){db.keys=db.keys.filter(k=>k.id!==id);db.messages=db.messages.filter(m=>m.keyId!==id);state.selectedKeys=(state.selectedKeys||[]).filter(x=>x!==id);save();renderNav();renderCurrent();toast('Đã xóa key')}}

function openPackage(id){state.page='package-form';state.edit=id||null;document.getElementById('sidebar').classList.remove('open');renderNav();renderCurrent()}
function editPackage(id){openPackage(id)}
function packageForm(){const id=state.edit,p=id?db.packages.find(x=>x.id===id):null;const end=localInputDate(p?.expires||'');return `<div class="form-page"><div class="form-page-head"><div><button class="back-btn" onclick="go('packages')">← Packages</button><div class="eyebrow">${id?'EDIT PACKAGE':'NEW PACKAGE'}</div><h1 class="title">${id?'Chỉnh sửa Package':'Tạo Package'}</h1><div class="sub">Cấu hình package, version, token, thiết bị và thời hạn.</div></div><div class="form-page-actions"><button class="secondary" onclick="go('packages')">Hủy</button><button class="primary" onclick="savePackageForm()">${id?'Lưu thay đổi':'Tạo Package'}</button></div></div><div class="form-layout"><div class="card"><h3>Thông tin Package</h3><div class="form two"><label>Tên package<input id="pName" value="${esc(p?.name||'New iOS Package')}"></label><label>Version<input id="pVersion" value="${esc(p?.version||'1.0.0')}"></label><label class="full">Package Token<input id="pToken" value="${esc(p?.token||makePackageToken())}" readonly><small>Token được sinh tự động và <b>không thể sửa</b>. Chỉ được tạo token mới khi tạo package.</small></label><label>Trạng thái<select id="pStatus"><option value="active" ${p?.status!=='paused'?'selected':''}>Active</option><option value="paused" ${p?.status==='paused'?'selected':''}>Paused</option></select></label><label>Giới hạn thiết bị<input id="pMaxDevices" type="number" min="1" value="${p?.maxDevices||500}"></label><label>Thời hạn<input id="pExpires" type="datetime-local" value="${end}"><small>Bỏ trống = vô hạn.</small></label><label class="full">Ghi chú<textarea id="pNotes" rows="5">${esc(p?.notes||'')}</textarea></label></div></div><div class="card package-token-large"><h3>Token Package</h3><code>${esc(p?.token||'Token sẽ được tạo khi lưu')}</code><div class="token-note">Token dài, ổn định theo package. Khi chỉnh sửa package, token hiện tại được giữ nguyên.</div></div></div></div>`}
function savePackageForm(){const id=state.edit,p=id?db.packages.find(x=>x.id===id):null;const name=document.getElementById('pName').value.trim(),version=document.getElementById('pVersion').value.trim(),token=document.getElementById('pToken').value.trim();if(!name||!version||!token){toast('Tên, version và token là bắt buộc');return}if(!p&&db.packages.some(x=>x.name.toLowerCase()===name.toLowerCase())){toast('Tên package đã tồn tại');return}const item={id:p?.id||Date.now(),name,version,status:document.getElementById('pStatus').value,devices:p?.devices||0,maxDevices:Math.max(1,Number(document.getElementById('pMaxDevices').value)||1),keys:p?.keys||0,token,expires:document.getElementById('pExpires').value,notes:document.getElementById('pNotes').value.trim()};if(p)Object.assign(p,item);else db.packages.push(item);save();state.edit=null;state.page='packages';renderNav();renderCurrent();toast(id?'Đã cập nhật package':'Đã tạo package')}
function togglePackage(id){let p=db.packages.find(x=>x.id===id);if(p){p.status=p.status==='active'?'paused':'active';save();renderCurrent();toast('Đã cập nhật trạng thái')}}
function deletePackage(id){if(confirm('Xóa package này?')){db.packages=db.packages.filter(p=>p.id!==id);save();renderCurrent();toast('Đã xóa package')}}

function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Đã copy')).catch(()=>toast('Không thể copy tự động'))}
function openMessage(keyId){let k=db.keys.find(x=>x.id===keyId);if(!k)return;modal(`Nhắn tin • ${esc(k.key)}`,`<div class="modal-sub">Tin nhắn được lưu theo key trong Firebase tại <code>nc_auth/messages</code>. Ứng dụng client cần đọc node này để hiển thị thông báo.</div><div class="form"><label>Loại thông báo<select id="mType"><option value="info">Thông tin</option><option value="success">Thành công</option><option value="warning">Cảnh báo</option><option value="update">Cập nhật</option></select></label><label>Tiêu đề<input id="mTitle" maxlength="120" placeholder="Ví dụ: Có bản cập nhật mới"></label><label>Nội dung<textarea id="mBody" rows="5" maxlength="1000" placeholder="Nhập nội dung gửi tới người dùng key..."></textarea></label><label>Hết hạn thông báo<input id="mExpires" type="datetime-local" value="${localInputDate(new Date(Date.now()+7*864e5).toISOString())}"></label></div>`);document.getElementById('modalSave').onclick=async()=>{let item={id:Date.now(),keyId:k.id,key:k.key,title:mTitle.value.trim(),body:mBody.value.trim(),type:mType.value,createdAt:new Date().toISOString(),expiresAt:mExpires.value,read:false};if(!item.title||!item.body){toast('Nhập tiêu đề và nội dung');return}db.messages.push(item);save();closeModal();renderCurrent();toast('Đã gửi tin nhắn cho key');};}
function exportKeys(){let csv='key,package,status,expires,devices,requests\n'+db.keys.map(k=>[k.key,k.package,k.status,k.expires,k.devices,k.requests].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='api-keys.csv';a.click();toast('Đã xuất CSV')}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='nc-auth-backup.json';a.click();toast('Đã xuất backup')}
async function resetData(){if(!confirm('Reset toàn bộ dữ liệu demo?'))return;db={keys:[],packages:[],messages:[]};storageSet('nc-auth-db',JSON.stringify(db));try{await firebasePut('nc_auth',{keys:[],packages:[],updatedAt:new Date().toISOString()});setFirebaseStatus('Firebase ✓',true)}catch(e){console.warn(e);setFirebaseStatus('Lưu lỗi',false)}renderNav();renderCurrent();closeModal();toast('Đã reset dữ liệu')}
function editName(){modal('Tên hiển thị',`<div class="form"><label>Display name<input id="newName" value="${esc(storageGet('display-name','Developer')||'Developer')}"></label></div>`);document.getElementById('modalSave').onclick=()=>{storageSet('display-name',newName.value.trim()||'Developer');closeModal();renderCurrent();toast('Đã lưu tên hiển thị')};}
async function copyCode(){let code=document.getElementById('code').textContent;try{await navigator.clipboard.writeText(code);toast('Đã copy code')}catch(e){toast('Hãy copy thủ công')}}
window.addEventListener('error',e=>{console.error(e.error||e.message);const c=document.getElementById('content');if(c&&!c.innerHTML)c.innerHTML='<div class="card"><h2>Không thể tải dashboard</h2><p class="muted">Hãy tải lại trang. Nếu lỗi tiếp tục, kiểm tra Console của trình duyệt.</p></div>'});window.addEventListener('unhandledrejection',e=>console.error(e.reason));try{if(storageGet('nc-theme')==='light')document.body.classList.add('light');renderNav();renderCurrent();refreshIcons();loadFirebase()}catch(e){console.error(e);const c=document.getElementById('content');if(c)c.innerHTML='<div class="card"><h2>Không thể tải dashboard</h2><p class="muted">Đã xảy ra lỗi khi khởi tạo giao diện.</p></div>'}
