const navItems=[['dashboard','Tổng quan','⌂'],['keys','API Keys','🔑'],['packages','Packages','▣'],['analytics','Analytics','▥'],['docs','Tài liệu','▤'],['pricing','Gói dịch vụ','◈'],['settings','Cài đặt','⚙']];
const FIREBASE_DB_URL='https://authsever-91133-default-rtdb.asia-southeast1.firebasedatabase.app';
const FIREBASE_AUTH_TOKEN='';
const DEFAULT_DB={keys:[{id:1,key:'NC-7K2A-9P4X',package:'ChatGPT iOS',status:'active',expires:'2026-12-31',devices:2,requests:12840,notes:'Production'}],packages:[{id:1,name:'ChatGPT iOS',version:'1.4.0',status:'active',devices:126,keys:1,token:'pk_live_nc_8f3d'}]};
function storageGet(key,fallback=''){try{return localStorage.getItem(key)??fallback}catch(e){return fallback}}
function storageSet(key,value){try{localStorage.setItem(key,value);return true}catch(e){console.warn('Storage unavailable',e);return false}}
function readLocalDb(){try{const raw=storageGet('nc-auth-db');if(!raw)return JSON.parse(JSON.stringify(DEFAULT_DB));const parsed=JSON.parse(raw);return normalizeDb(parsed)}catch(e){console.warn('Invalid local data',e);return JSON.parse(JSON.stringify(DEFAULT_DB))}}
function normalizeDb(raw){const x=raw&&typeof raw==='object'?raw:{};return{keys:Array.isArray(x.keys)?x.keys.map((k,i)=>({id:k.id??Date.now()+i,key:String(k.key??''),package:String(k.package??''),status:k.status==='paused'?'paused':'active',expires:String(k.expires??''),devices:Math.max(0,Number(k.devices)||0),requests:Math.max(0,Number(k.requests)||0),notes:String(k.notes??'')})):[],packages:Array.isArray(x.packages)?x.packages.map((p,i)=>({id:p.id??Date.now()+i,name:String(p.name??''),version:String(p.version??''),status:p.status==='paused'?'paused':'active',devices:Math.max(0,Number(p.devices)||0),keys:Math.max(0,Number(p.keys)||0),token:String(p.token??'')})):[]}}
let db=readLocalDb();
let state={page:'dashboard',edit:null};
function firebaseUrl(path){let u=FIREBASE_DB_URL.replace(/\/$/,'')+'/'+path+'.json';return FIREBASE_AUTH_TOKEN?u+'?auth='+encodeURIComponent(FIREBASE_AUTH_TOKEN):u}
function setFirebaseStatus(text,ok){let e=document.getElementById('firebaseStatus');if(e){e.textContent=text;e.style.color=ok?'var(--good)':'var(--warn)'}}
async function firebaseGet(path){let r=await fetch(firebaseUrl(path),{cache:'no-store'});if(!r.ok)throw new Error('Firebase GET '+r.status);return r.json()}
async function firebasePut(path,data){let r=await fetch(firebaseUrl(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('Firebase PUT '+r.status);return r.json()}
async function loadFirebase(){setFirebaseStatus('Đang tải…',false);try{let remote=await firebaseGet('nc_auth');if(remote&&typeof remote==='object'){db=normalizeDb({keys:Array.isArray(remote.keys)?remote.keys:db.keys,packages:Array.isArray(remote.packages)?remote.packages:db.packages});storageSet('nc-auth-db',JSON.stringify(db));renderNav();renderCurrent()}setFirebaseStatus('Firebase ✓',true)}catch(e){console.warn(e);setFirebaseStatus('Firebase offline',false);toast('Không đọc được Firebase — đang dùng dữ liệu local')}}
async function syncFirebase(){try{setFirebaseStatus('Đang lưu…',false);await firebasePut('nc_auth',{keys:db.keys,packages:db.packages,updatedAt:new Date().toISOString()});setFirebaseStatus('Firebase ✓',true);return true}catch(e){console.error(e);setFirebaseStatus('Lưu lỗi',false);toast('Firebase chưa cho phép ghi dữ liệu');return false}}
function save(){db=normalizeDb(db);storageSet('nc-auth-db',JSON.stringify(db));syncFirebase()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(m){let e=document.getElementById('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2500)}
function toggleSide(){document.getElementById('sidebar').classList.toggle('open')}
function go(p){state.page=p;document.getElementById('sidebar').classList.remove('open');if(p!=='keys'&&p!=='packages')document.getElementById('globalSearch').value='';renderNav();renderCurrent()}
function renderNav(){document.getElementById('nav').innerHTML=navItems.map(([id,l,i])=>`<button class="${state.page===id?'active':''}" onclick="go('${id}')">${i}<span>${l}</span>${id==='keys'?'<span class="badge">'+db.keys.length+'</span>':''}</button>`).join('')}
function toggleTheme(){document.body.classList.toggle('light');storageSet('nc-theme',document.body.classList.contains('light')?'light':'dark')}
function stat(label,val,delta){return `<div class="card"><div class="stat-label">${label}</div><div class="stat">${val}</div><div class="delta">${delta}</div></div>`}
function dashboard(){let req=db.keys.reduce((a,k)=>a+(Number(k.requests)||0),0);return `<div class="eyebrow">Nguyễn Cường iOS</div><h1 class="title">Xin chào, Developer 👋</h1><div class="sub">Quản lý KeyAuth, package và hoạt động API trong một workspace.</div><div class="hero"><div><span class="tag">PRO WORKSPACE</span><h2>iOS KeyAuth Manager</h2><p>Không cần đăng nhập. Dữ liệu demo được lưu trực tiếp trên thiết bị bằng localStorage.</p></div><div class="actions"><button class="primary" onclick="openKey()">+ Tạo API Key</button><button class="secondary" onclick="go('docs')">Xem tài liệu</button></div></div><div class="stats">${stat('Packages',db.packages.length,'↑ Workspace')} ${stat('API Keys',db.keys.length,'↑ Quản lý')} ${stat('Requests',req.toLocaleString(),'↑ Tổng requests')} ${stat('Hoạt động','99.9%','● Hệ thống ổn định')}</div><div class="grid2"><div class="card"><h3>API usage • 7 ngày</h3><div class="chart">${[42,58,46,74,61,89,68,78,54,91,70,84,63,76].map(v=>`<div class="bar" style="height:${v}%"></div>`).join('')}</div></div><div class="card"><h3>Hoạt động gần đây</h3><div class="activity">${db.keys.slice(0,4).map(k=>`<div class="activity-row"><span>Key <b>${esc(k.key)}</b><br><span class="muted">${esc(k.package)}</span></span><span class="muted">vừa xong</span></div>`).join('')||'<div class="empty">Chưa có hoạt động</div>'}</div></div></div>`}
function keys(){let q=(document.getElementById('globalSearch').value||'').toLowerCase();let rows=db.keys.filter(k=>Object.values(k).join(' ').toLowerCase().includes(q));return `<div class="eyebrow">Management</div><h1 class="title">API Keys</h1><div class="sub">Tạo, chỉnh sửa, tạm dừng và xuất danh sách key.</div><div class="toolbar"><div class="toolbar-left"><input class="input" placeholder="Tìm key..." value="${esc(q)}" oninput="document.getElementById('globalSearch').value=this.value;renderCurrent()"></div><div class="toolbar-right"><button class="secondary" onclick="exportKeys()">Xuất CSV</button><button class="primary" onclick="openKey()">+ Tạo key</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>KEY</th><th>PACKAGE</th><th>STATUS</th><th>EXPIRES</th><th>DEVICES</th><th>REQUESTS</th><th></th></tr></thead><tbody>${rows.map(k=>`<tr><td><b>${esc(k.key)}</b><br><span class="muted">${esc(k.notes)}</span></td><td>${esc(k.package)}</td><td><span class="pill ${k.status==='active'?'green':''}">${k.status==='active'?'Active':'Paused'}</span></td><td>${esc(k.expires)}</td><td>${k.devices}</td><td>${(Number(k.requests)||0).toLocaleString()}</td><td><button class="secondary" onclick="editKey(${k.id})">Sửa</button> <button class="secondary" onclick="toggleKey(${k.id})">${k.status==='active'?'Pause':'Resume'}</button> <button class="secondary" onclick="deleteKey(${k.id})">Xóa</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">Không tìm thấy key.</div></td></tr>'}</tbody></table></div>`}
function packages(){let keyCounts=db.keys.reduce((m,k)=>(m[k.package]=(m[k.package]||0)+1,m),{});let q=(document.getElementById('globalSearch').value||'').toLowerCase();let rows=db.packages.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));return `<div class="eyebrow">Workspace</div><h1 class="title">Packages</h1><div class="sub">Quản lý các package iOS và token tích hợp.</div><div class="toolbar"><input class="input" placeholder="Tìm package..." value="${esc(q)}" oninput="document.getElementById('globalSearch').value=this.value;renderCurrent()"><button class="primary" onclick="openPackage()">+ Tạo package</button></div><div class="table-wrap"><table class="table"><thead><tr><th>PACKAGE</th><th>VERSION</th><th>STATUS</th><th>DEVICES</th><th>KEYS</th><th>TOKEN</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.version)}</td><td><span class="pill ${p.status==='active'?'green':''}">${p.status}</span></td><td>${p.devices}</td><td>${keyCounts[p.name]||p.keys||0}</td><td><code>${esc(p.token)}</code></td><td><button class="secondary" onclick="editPackage(${p.id})">Sửa</button> <button class="secondary" onclick="togglePackage(${p.id})">${p.status==='active'?'Pause':'Resume'}</button> <button class="secondary" onclick="deletePackage(${p.id})">Xóa</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">Chưa có package.</div></td></tr>'}</tbody></table></div>`}
function analytics(){let total=db.keys.reduce((a,k)=>a+(Number(k.requests)||0),0);return `<div class="eyebrow">Insights</div><h1 class="title">Analytics</h1><div class="sub">Theo dõi requests và trạng thái workspace.</div><div class="stats">${stat('Requests',total.toLocaleString(),'7 ngày')} ${stat('Errors','0.08%','↓ 12%')} ${stat('Latency','84 ms','↓ 9 ms')} ${stat('Uptime','99.9%','Ổn định')}</div><div class="grid2"><div class="card"><h3>Requests theo ngày</h3><div class="chart">${[35,44,57,51,68,73,62,79,84,71,88,91,76,86,94].map(v=>`<div class="bar" style="height:${v}%"></div>`).join('')}</div></div><div class="card"><h3>Top packages</h3><div class="activity">${db.packages.map((p,i)=>`<div class="activity-row"><b>${esc(p.name)}</b><span>${((Number(p.devices)||0)*97).toLocaleString()} req</span></div>`).join('')||'<div class="empty">Chưa có dữ liệu</div>'}</div></div></div>`}
function docs(){let tab=state.docsTab||'Overview';let samples={Overview:`// KeyAuth integration\nlet auth = Auth.shared\nauth.authenticate("YOUR_TOKEN") { result in\n    if result.isSuccess {\n        print("Authenticated")\n    }\n}`,"API Reference":`authenticate(token)\n// Validate a key/token against your service.\n\nrevoke(key)\n// Revoke an active key.\n\nstatus(key)\n// Read key status and expiration.`,SDK:`// iOS / Theos\n// Keep the SDK token in your protected configuration.\n\nAuth.shared.authenticate("YOUR_TOKEN")`,Examples:`// Example flow\ncreate package\n  -> create API key\n  -> authenticate\n  -> check expiration\n  -> handle revoked / paused state`};let code=samples[tab];return `<div class="eyebrow">Developer</div><h1 class="title">Tài liệu</h1><div class="sub">Tích hợp nhanh trong dự án iOS / Theos.</div><div class="docs-tabs">${Object.keys(samples).map(t=>`<button class="${tab===t?'active':''}" onclick="setDocsTab('${t}')">${t}</button>`).join('')}</div><div class="grid2"><div class="card"><h3>${tab}</h3><p class="muted">${tab==='Overview'?'1. Tạo package → 2. Tạo API key → 3. Đưa token vào SDK → 4. Gọi authenticate.':tab==='API Reference'?'Các method cơ bản cho luồng xác thực và quản lý key.':tab==='SDK'?'Thông tin tương thích và cách khởi tạo SDK.':'Luồng mẫu từ tạo package đến xác thực.'}</p><button class="primary" onclick="copyCode()">Copy example</button></div><div class="card"><h3>Example</h3><pre class="code" id="code">${esc(code)}</pre></div></div><div class="card" style="margin-top:14px"><h3>SDK compatibility</h3><p class="muted">iOS 12+ • arm64 • arm64e • Keychain • expired-key handling • REST/RTDB dashboard.</p></div>`}
function setDocsTab(tab){state.docsTab=tab;renderCurrent()}

function pricing(){let plans=[['Free','0','Cho dự án cá nhân'],['Developer','9','Dành cho developer'],['Seller','29','Quản lý nhiều package'],['SupperSeller','79','Workspace nâng cao']];return `<div class="eyebrow">Plans</div><h1 class="title">Gói dịch vụ</h1><div class="sub">Chọn workspace phù hợp. Demo này xử lý nâng cấp bằng thông báo cục bộ.</div><div class="price-grid">${plans.map((p,i)=>`<div class="card price ${i===1?'pop':''}">${i===1?'<span class="tag">PHỔ BIẾN</span>':''}<h3>${p[0]}</h3><strong>$${p[1]}</strong><span class="muted"> / tháng</span><p class="muted">${p[2]}</p><ul><li>API key management</li><li>Package management</li><li>Analytics</li><li>Documentation</li></ul><button class="${i===1?'primary':'secondary'}" onclick="toast('${p[0]}: nâng cấp demo đã sẵn sàng')">${i===0?'Đang dùng':'Nâng cấp'}</button></div>`).join('')}</div>`}
function settings(){let light=document.body.classList.contains('light');return `<div class="eyebrow">Workspace</div><h1 class="title">Cài đặt</h1><div class="sub">Tuỳ chỉnh giao diện và đồng bộ dữ liệu với Firebase Realtime Database.</div><div class="settings-grid"><div class="card"><h3>Giao diện</h3><div class="setting"><div><b>Chế độ sáng</b><small>Đổi dark / light</small></div><button class="switch ${light?'on':''}" onclick="toggleTheme();renderCurrent()"><i></i></button></div><div class="setting"><div><b>Màu nhấn</b><small>Pink • #ff3d91</small></div><span class="pill pink">PINK</span></div></div><div class="card"><h3>Firebase Realtime Database</h3><div class="setting"><div><b>Kết nối</b><small>authsever-91133-default-rtdb • /nc_auth</small></div><span class="pill pink">RTDB</span></div><div class="setting"><div><b>Đồng bộ</b><small>Mỗi lần tạo/sửa/xóa key hoặc package sẽ lưu lên Firebase.</small></div><button class="secondary" onclick="loadFirebase()">Sync</button></div></div><div class="card"><h3>Hồ sơ & dữ liệu</h3><div class="setting"><div><b>Tên hiển thị</b><small>Được lưu trên thiết bị</small></div><button class="secondary" onclick="editName()">Sửa</button></div><div class="setting"><div><b>Backup JSON</b><small>Xuất dữ liệu local</small></div><button class="secondary" onclick="backup()">Xuất</button></div><div class="setting"><div><b>Xoá dữ liệu demo</b><small>Không thể hoàn tác</small></div><button class="secondary" onclick="resetData()">Reset</button></div></div></div>`}
function renderCurrent(){let fn={dashboard,keys,packages,analytics,docs,pricing,settings}[state.page]||dashboard;document.getElementById('content').innerHTML=fn();document.getElementById('mobileTitle').textContent=navItems.find(x=>x[0]===state.page)?.[1]||'Tổng quan';document.getElementById('profileName').textContent=storageGet('display-name','Developer')||'Developer'}
function modal(title,body){document.getElementById('modal').innerHTML=`<h3>${title}</h3>${body}<div class="modal-actions"><button class="secondary" onclick="closeModal()">Hủy</button><button class="primary" id="modalSave">Lưu</button></div>`;document.getElementById('modalBg').classList.add('show')}
function closeModal(){document.getElementById('modalBg').classList.remove('show')}
function openKey(id){let k=id?db.keys.find(x=>x.id===id):null;modal(id?'Sửa API Key':'Tạo API Key',`<div class="form"><label>Key<input id="fKey" value="${esc(k?.key||'NC-'+Math.random().toString(36).slice(2,10).toUpperCase())}"></label><label>Package<input id="fPackage" value="${esc(k?.package||db.packages[0]?.name||'ChatGPT iOS')}"></label><label>Expires<input id="fExpires" type="date" value="${esc(k?.expires||'2026-12-31')}"></label><label>Devices<input id="fDevices" type="number" value="${k?.devices||1}"></label><label>Notes<textarea id="fNotes">${esc(k?.notes||'')}</textarea></label></div>`);document.getElementById('modalSave').onclick=()=>{let item={id:k?.id||Date.now(),key:fKey.value.trim(),package:fPackage.value.trim(),status:k?.status||'active',expires:fExpires.value,devices:Math.max(1,Number(fDevices.value)||1),requests:k?.requests||0,notes:fNotes.value.trim()};if(!item.key||!item.package){toast('Vui lòng nhập đủ thông tin');return}if(k)Object.assign(k,item);else db.keys.push(item);save();closeModal();renderNav();renderCurrent();toast('Đã lưu API Key')};}
function editKey(id){openKey(id)}function toggleKey(id){let k=db.keys.find(x=>x.id===id);if(k){k.status=k.status==='active'?'paused':'active';save();renderCurrent();toast(k.status==='active'?'Đã resume key':'Đã pause key')}}function deleteKey(id){if(confirm('Xóa API key này?')){db.keys=db.keys.filter(k=>k.id!==id);save();renderNav();renderCurrent();toast('Đã xóa key')}}
function openPackage(id){let p=id?db.packages.find(x=>x.id===id):null;modal(id?'Sửa Package':'Tạo Package',`<div class="form"><label>Name<input id="pName" value="${esc(p?.name||'New iOS Package')}"></label><label>Version<input id="pVersion" value="${esc(p?.version||'1.0.0')}"></label><label>Token<input id="pToken" value="${esc(p?.token||'pk_live_'+Math.random().toString(36).slice(2,9))}"></label></div>`);document.getElementById('modalSave').onclick=()=>{let item={id:p?.id||Date.now(),name:pName.value.trim(),version:pVersion.value.trim(),status:p?.status||'active',devices:p?.devices||0,keys:p?.keys||0,token:pToken.value.trim()};if(!item.name||!item.version){toast('Vui lòng nhập đủ thông tin');return}if(p)Object.assign(p,item);else db.packages.push(item);save();closeModal();renderCurrent();toast('Đã lưu package')};}
function editPackage(id){openPackage(id)}function togglePackage(id){let p=db.packages.find(x=>x.id===id);if(p){p.status=p.status==='active'?'paused':'active';save();renderCurrent();toast('Đã cập nhật trạng thái')}}function deletePackage(id){if(confirm('Xóa package này?')){db.packages=db.packages.filter(p=>p.id!==id);save();renderCurrent();toast('Đã xóa package')}}
function exportKeys(){let csv='key,package,status,expires,devices,requests\n'+db.keys.map(k=>[k.key,k.package,k.status,k.expires,k.devices,k.requests].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='api-keys.csv';a.click();toast('Đã xuất CSV')}
function backup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='nc-auth-backup.json';a.click();toast('Đã xuất backup')}
async function resetData(){if(!confirm('Reset toàn bộ dữ liệu demo?'))return;db={keys:[],packages:[]};storageSet('nc-auth-db',JSON.stringify(db));try{await firebasePut('nc_auth',{keys:[],packages:[],updatedAt:new Date().toISOString()});setFirebaseStatus('Firebase ✓',true)}catch(e){console.warn(e);setFirebaseStatus('Lưu lỗi',false)}renderNav();renderCurrent();closeModal();toast('Đã reset dữ liệu')}
function editName(){modal('Tên hiển thị',`<div class="form"><label>Display name<input id="newName" value="${esc(storageGet('display-name','Developer')||'Developer')}"></label></div>`);document.getElementById('modalSave').onclick=()=>{storageSet('display-name',newName.value.trim()||'Developer');closeModal();renderCurrent();toast('Đã lưu tên hiển thị')};}
async function copyCode(){let code=document.getElementById('code').textContent;try{await navigator.clipboard.writeText(code);toast('Đã copy code')}catch(e){toast('Hãy copy thủ công')}}
window.addEventListener('error',e=>{console.error(e.error||e.message);const c=document.getElementById('content');if(c&&!c.innerHTML)c.innerHTML='<div class="card"><h2>Không thể tải dashboard</h2><p class="muted">Hãy tải lại trang. Nếu lỗi tiếp tục, kiểm tra Console của trình duyệt.</p></div>'});window.addEventListener('unhandledrejection',e=>console.error(e.reason));try{if(storageGet('nc-theme')==='light')document.body.classList.add('light');renderNav();renderCurrent();loadFirebase()}catch(e){console.error(e);const c=document.getElementById('content');if(c)c.innerHTML='<div class="card"><h2>Không thể tải dashboard</h2><p class="muted">Đã xảy ra lỗi khi khởi tạo giao diện.</p></div>'}
